test_type: normal
data:
  dataset: imagenet
  train_dir: data/raw
  test_dir: data/raw
  batch_size: 256
crypto:
  algorithm: ed25519
  sk_path: data/keys/backdoor/sk_imagenet_ed25519.bin
  pk_path: data/keys/backdoor/pk_imagenet_ed25519.bin
model:
  type: resnet18
  ckpt_path: models/resnet18.pth